import "server-only";
import { db } from "@/db";
import { activities, messages, deals, pipelineStages } from "@/db/schema";
import {
  getUnreadMessages,
  getGmailMessage,
  extractFromAddress,
  extractInReplyToMessageId,
} from "@/lib/integrations/gmail-multi";
import { eq } from "drizzle-orm";

export type SyncRepliesResult = {
  repliesFound: number;
  stagesUpdated: number;
  bouncesFound: number;
  errors: string[];
};

/** Sender/subject heuristics for a delivery-failure notice — Gmail (and most other MTAs) send these from a "Mail Delivery Subsystem"-style address rather than the recipient. There's no structured bounce API to call instead; this is the same approach every inbox-polling integration without provider-side bounce webhooks falls back to. */
function looksLikeBounce(fromAddress: string, subject: string): boolean {
  if (/mailer-daemon|postmaster/i.test(fromAddress)) return true;
  return /^(delivery status notification|undelivered mail returned to sender|mail delivery failed|delivery (has )?failed|returned mail|delivery incomplete)/i.test(
    subject.trim()
  );
}

/**
 * Core Gmail reply-sync logic (Phase 3/4), shared by the session-protected
 * manual-trigger route (src/app/api/emails/sync-replies) and the
 * bearer-secret cron route (src/app/api/cron/sync-replies) that a Zo
 * background loop hits on a schedule. Polls all 3 rotating Gmail accounts
 * for unread replies to our outbound emails, logs them as inbound
 * activities, bumps the deal to the "responded/conversation" stage, and
 * (since Gmail/most MTAs bounce by emailing us back rather than calling a
 * webhook) flags any delivery-failure notice back onto the sent message it
 * bounced for — see looksLikeBounce above.
 */
export async function syncReplies(): Promise<SyncRepliesResult> {
  let repliesFound = 0;
  let stagesUpdated = 0;
  let bouncesFound = 0;
  const errors: string[] = [];

  for (let accountIndex = 0; accountIndex < 3; accountIndex++) {
    try {
      const unreadResponse = await getUnreadMessages(accountIndex as any);

      if (!unreadResponse.messages) continue;

      for (const msgRef of unreadResponse.messages) {
        try {
          const fullMsg = await getGmailMessage(accountIndex as any, msgRef.id!);
          const headers = fullMsg.payload?.headers || [];

          const fromAddress = extractFromAddress(headers);
          const subjectHeader =
            headers.find((h: { name?: string | null; value?: string | null }) => h.name === "Subject")
              ?.value || "";

          if (looksLikeBounce(fromAddress, subjectHeader)) {
            // A bounce carries no In-Reply-To we can trust (the failure
            // notice is generated by the recipient's mail server, not the
            // original sender), so it's matched by Gmail thread id instead
            // — the bounce lands in the same thread as the send that failed.
            const threadId = fullMsg.threadId;
            const bouncedMessage = threadId
              ? await db.query.messages.findFirst({
                  where: (m, { eq, and, inArray } ) =>
                    and(eq(m.threadId, threadId), inArray(m.status, ["sent", "delivered", "opened"])),
                  orderBy: (m, { desc }) => desc(m.createdAt),
                })
              : null;

            if (bouncedMessage) {
              await db
                .update(messages)
                .set({
                  status: "bounced",
                  bouncedAt: new Date(),
                  bounceReason: fullMsg.snippet || subjectHeader || "Delivery failed",
                })
                .where(eq(messages.id, bouncedMessage.id));
              bouncesFound++;
            }
            continue;
          }

          const inReplyToId = extractInReplyToMessageId(headers);

          if (!inReplyToId) continue; // Not a reply to our email

          const sentMessage = await db.query.messages.findFirst({
            where: (m, { eq }) => eq(m.providerMessageId, inReplyToId),
            with: {
              activity: {
                with: {
                  deal: {
                    with: {
                      stage: true,
                    },
                  },
                },
              },
            },
          });

          if (!sentMessage) continue;

          const replyBody = fullMsg.payload?.parts?.[0]?.body?.data
            ? Buffer.from(fullMsg.payload.parts[0].body.data, "base64").toString()
            : "Reply received";

          const replyActivity = await db
            .insert(activities)
            .values({
              companyId: sentMessage.activity.companyId,
              contactId: sentMessage.activity.contactId,
              dealId: sentMessage.activity.dealId,
              type: "email",
              direction: "inbound",
              bodyText: replyBody,
              aiGenerated: false,
            })
            .returning();

          await db
            .insert(messages)
            .values({
              activityId: replyActivity[0].id,
              provider: "gmail",
              providerMessageId: msgRef.id!,
              threadId: fullMsg.threadId,
              accountIndex,
              status: "replied",
              fromAddress,
              toAddress: sentMessage.toAddress,
              subject: `Re: ${sentMessage.subject}`,
              body: replyBody,
              generatedByAi: false,
            })
            .returning();

          repliesFound++;

          await db.update(messages).set({ status: "replied" }).where(eq(messages.id, sentMessage.id));

          if (sentMessage.activity.deal) {
            const responseStage = await db.query.pipelineStages.findFirst({
              where: (ps, { ilike }) => ilike(ps.name, "%responded%") || ilike(ps.name, "%conversation%"),
            });

            if (responseStage && sentMessage.activity.deal.stageId !== responseStage.id) {
              await db
                .update(deals)
                .set({
                  stageId: responseStage.id,
                  stageEnteredAt: new Date(),
                  updatedAt: new Date(),
                })
                .where(eq(deals.id, sentMessage.activity.deal.id));

              stagesUpdated++;
            }
          }
        } catch (msgErr) {
          errors.push(`Failed to process message ${msgRef.id}: ${String(msgErr)}`);
        }
      }
    } catch (accountErr) {
      errors.push(`Failed to sync account ${accountIndex + 1}: ${String(accountErr)}`);
    }
  }

  return { repliesFound, stagesUpdated, bouncesFound, errors };
}
